"""Export diff results to various output formats (JSON, CSV, shell script)."""

from __future__ import annotations

import csv
import io
import json
from typing import Literal

from envdiff.diff import EnvDiffResult

OutputFormat = Literal["json", "csv", "shell"]


def export_json(result: EnvDiffResult, indent: int = 2) -> str:
    """Serialize diff result to a JSON string."""
    payload = {
        "only_in_left": {k: result.only_in_left[k] for k in sorted(result.only_in_left)},
        "only_in_right": {k: result.only_in_right[k] for k in sorted(result.only_in_right)},
        "changed": {
            k: {"left": lv, "right": rv}
            for k, (lv, rv) in sorted(result.changed.items())
        },
        "unchanged": {k: result.unchanged[k] for k in sorted(result.unchanged)},
    }
    return json.dumps(payload, indent=indent)


def export_csv(result: EnvDiffResult) -> str:
    """Serialize diff result to a CSV string with columns: key, status, left, right."""
    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["key", "status", "left", "right"])

    for key in sorted(result.only_in_left):
        writer.writerow([key, "removed", result.only_in_left[key], ""])

    for key in sorted(result.only_in_right):
        writer.writerow([key, "added", "", result.only_in_right[key]])

    for key, (lv, rv) in sorted(result.changed.items()):
        writer.writerow([key, "changed", lv, rv])

    for key in sorted(result.unchanged):
        writer.writerow([key, "unchanged", result.unchanged[key], result.unchanged[key]])

    return buf.getvalue()


def export_shell(result: EnvDiffResult, target: Literal["left", "right"] = "right") -> str:
    """Generate a shell script that applies the diff to reach the *target* state."""
    lines: list[str] = ["#!/usr/bin/env sh", "# Generated by envdiff exporter", ""]

    if target == "right":
        for key in sorted(result.only_in_left):
            lines.append(f"unset {key}")
        for key in sorted(result.only_in_right):
            lines.append(f"export {key}={_shell_quote(result.only_in_right[key])}")
        for key, (_lv, rv) in sorted(result.changed.items()):
            lines.append(f"export {key}={_shell_quote(rv)}")
    else:
        for key in sorted(result.only_in_right):
            lines.append(f"unset {key}")
        for key in sorted(result.only_in_left):
            lines.append(f"export {key}={_shell_quote(result.only_in_left[key])}")
        for key, (lv, _rv) in sorted(result.changed.items()):
            lines.append(f"export {key}={_shell_quote(lv)}")

    return "\n".join(lines) + "\n"


def _shell_quote(value: str) -> str:
    """Wrap value in single quotes, escaping any embedded single quotes."""
    escaped = value.replace("'", "'\"'\"'")
    return f"'{escaped}'"


def export(result: EnvDiffResult, fmt: OutputFormat = "json", **kwargs) -> str:
    """Dispatch to the appropriate exporter based on *fmt*."""
    if fmt == "json":
        return export_json(result, **kwargs)
    if fmt == "csv":
        return export_csv(result)
    if fmt == "shell":
        return export_shell(result, **kwargs)
    raise ValueError(f"Unsupported export format: {fmt!r}")
